player_manager.AddValidModel( "CSGO - Bare Hand", "models/kyo/weapons/v_bare_hands.mdl" )
player_manager.AddValidHands( "CSGO - Bare Hand", "models/kyo/weapons/v_bare_hands.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - Bloodhound Glove", "models/kyo/weapons/v_glove_bloodhound.mdl" )
player_manager.AddValidHands( "CSGO - Bloodhound Glove", "models/kyo/weapons/v_glove_bloodhound.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - Bloodhound Glove - Hydra", "models/kyo/weapons/v_glove_bloodhound_fingerless_hydra.mdl" )
player_manager.AddValidHands( "CSGO - Bloodhound Glove - Hydra", "models/kyo/weapons/v_glove_bloodhound_fingerless_hydra.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - Bloodhound Glove - Broken Fang", "models/kyo/weapons/v_glove_bloodhound_fingerless_brokenfang.mdl" )
player_manager.AddValidHands( "CSGO - Bloodhound Glove - Broken Fang", "models/kyo/weapons/v_glove_bloodhound_fingerless_brokenfang.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - CT Default", "models/kyo/weapons/v_glove_ct_hardknuckle.mdl" )
player_manager.AddValidHands( "CSGO - CT Default", "models/kyo/weapons/v_glove_ct_hardknuckle.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - CT Default - Black", "models/kyo/weapons/v_glove_ct_hardknuckle_black.mdl" )
player_manager.AddValidHands( "CSGO - CT Default - Black", "models/kyo/weapons/v_glove_ct_hardknuckle_black.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - CT Default - Blue", "models/kyo/weapons/v_glove_ct_hardknuckle_blue.mdl" )
player_manager.AddValidHands( "CSGO - CT Default - Blue", "models/kyo/weapons/v_glove_ct_hardknuckle_blue.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - Specialist Gloves", "models/kyo/weapons/v_glove_ct_specialist.mdl" )
player_manager.AddValidHands( "CSGO - Specialist Gloves", "models/kyo/weapons/v_glove_ct_specialist.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - T Default", "models/kyo/weapons/v_glove_fingerless.mdl" )
player_manager.AddValidHands( "CSGO - T Default", "models/kyo/weapons/v_glove_fingerless.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - T Fullfinger", "models/kyo/weapons/v_glove_fullfinger.mdl" )
player_manager.AddValidHands( "CSGO - T Fullfinger", "models/kyo/weapons/v_glove_fullfinger.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - Handwrap Gloves", "models/kyo/weapons/v_glove_handwrap_leathery.mdl" )
player_manager.AddValidHands( "CSGO - Handwrap Gloves", "models/kyo/weapons/v_glove_handwrap_leathery.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - Moto Gloves", "models/kyo/weapons/v_glove_motorcycle.mdl" )
player_manager.AddValidHands( "CSGO - Moto Gloves", "models/kyo/weapons/v_glove_motorcycle.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - Slick Gloves", "models/kyo/weapons/v_glove_slick.mdl" )
player_manager.AddValidHands( "CSGO - Slick Gloves", "models/kyo/weapons/v_glove_slick.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - Sport Gloves", "models/kyo/weapons/v_glove_sporty.mdl" )
player_manager.AddValidHands( "CSGO - Sport Gloves", "models/kyo/weapons/v_glove_sporty.mdl", 0, "00" )
player_manager.AddValidModel( "CSGO - Legacy Gloves", "models/kyo/weapons/mix_arms_old.mdl" )
player_manager.AddValidHands( "CSGO - Legacy Gloves", "models/kyo/weapons/mix_arms_old.mdl", 0, "00" )