local _, Icons = debug.getupvalue(killicon.Add, 1)
local COLOR_ICON = Color(255, 80, 0)

function swcs.AddKillicon(classname, path)
	-- manually created so we can set smooth
	local mat = Material(path, "smooth")
	mat:SetInt("$flags", bit.bor(mat:GetInt("$flags"), 128)) -- $additive
	mat:Recompute()

	Icons[classname] = {
		type = 1,
		color = COLOR_ICON,
		material = mat,
		texture = surface.GetTextureID("hud/killicons/default.vmt"),
	}
end

swcs.AddKillicon("swcs_inferno", "hud/swcs/select/inferno.png")

swcs.AddKillicon("weapon_swcs_ak47", "hud/swcs/select/ak47.png")
swcs.AddKillicon("weapon_swcs_aug", "hud/swcs/select/aug.png")
swcs.AddKillicon("weapon_swcs_awp", "hud/swcs/select/awp.png")
swcs.AddKillicon("weapon_swcs_bizon", "hud/swcs/select/bizon.png")
swcs.AddKillicon("weapon_swcs_cz75", "hud/swcs/select/cz75a.png")
swcs.AddKillicon("weapon_swcs_deagle", "hud/swcs/select/deagle.png")
swcs.AddKillicon("weapon_swcs_elite", "hud/swcs/select/elite.png")
swcs.AddKillicon("weapon_swcs_famas", "hud/swcs/select/famas.png")
swcs.AddKillicon("weapon_swcs_fiveseven", "hud/swcs/select/fiveseven.png")
swcs.AddKillicon("weapon_swcs_g3sg1", "hud/swcs/select/g3sg1.png")
swcs.AddKillicon("weapon_swcs_galilar", "hud/swcs/select/galilar.png")
swcs.AddKillicon("weapon_swcs_glock", "hud/swcs/select/glock.png")
swcs.AddKillicon("weapon_swcs_hkp2000", "hud/swcs/select/hkp2000.png")
swcs.AddKillicon("weapon_swcs_m4a1", "hud/swcs/select/m4a1.png")
swcs.AddKillicon("weapon_swcs_m4a1_silencer", "hud/swcs/select/m4a1_silencer.png")
swcs.AddKillicon("weapon_swcs_m249", "hud/swcs/select/m249.png")
swcs.AddKillicon("weapon_swcs_mac10", "hud/swcs/select/mac10.png")
swcs.AddKillicon("weapon_swcs_mag7", "hud/swcs/select/mag7.png")
swcs.AddKillicon("weapon_swcs_mp5sd", "hud/swcs/select/mp5sd.png")
swcs.AddKillicon("weapon_swcs_mp7", "hud/swcs/select/mp7.png")
swcs.AddKillicon("weapon_swcs_mp9", "hud/swcs/select/mp9.png")
swcs.AddKillicon("weapon_swcs_negev", "hud/swcs/select/negev.png")
swcs.AddKillicon("weapon_swcs_nova", "hud/swcs/select/nova.png")
swcs.AddKillicon("weapon_swcs_p90", "hud/swcs/select/p90.png")
swcs.AddKillicon("weapon_swcs_p250", "hud/swcs/select/p250.png")
swcs.AddKillicon("weapon_swcs_revolver", "hud/swcs/select/revolver.png")
swcs.AddKillicon("weapon_swcs_sawedoff", "hud/swcs/select/sawedoff.png")
swcs.AddKillicon("weapon_swcs_scar20", "hud/swcs/select/scar20.png")
swcs.AddKillicon("weapon_swcs_sg556", "hud/swcs/select/sg556.png")
swcs.AddKillicon("weapon_swcs_ssg08", "hud/swcs/select/ssg08.png")
swcs.AddKillicon("weapon_swcs_taser", "hud/swcs/select/taser.png")
swcs.AddKillicon("weapon_swcs_tec9", "hud/swcs/select/tec9.png")
swcs.AddKillicon("weapon_swcs_ump45", "hud/swcs/select/ump45.png")
swcs.AddKillicon("weapon_swcs_usp_silencer", "hud/swcs/select/usp_silencer.png")
swcs.AddKillicon("weapon_swcs_xm1014", "hud/swcs/select/xm1014.png")

swcs.AddKillicon("weapon_swcs_knife_ct", "hud/swcs/select/knife.png")
swcs.AddKillicon("weapon_swcs_knife_t", "hud/swcs/select/knife_t.png")
swcs.AddKillicon("weapon_swcs_bayonet", "hud/swcs/select/bayonet.png")
swcs.AddKillicon("weapon_swcs_knife_butterfly", "hud/swcs/select/knife_butterfly.png")
swcs.AddKillicon("weapon_swcs_knife_canis", "hud/swcs/select/knife_canis.png")
swcs.AddKillicon("weapon_swcs_knife_cord", "hud/swcs/select/knife_cord.png")
swcs.AddKillicon("weapon_swcs_knife_css", "hud/swcs/select/knife_css.png")
swcs.AddKillicon("weapon_swcs_knife_falchion", "hud/swcs/select/knife_falchion.png")
swcs.AddKillicon("weapon_swcs_knife_flip", "hud/swcs/select/knife_flip.png")
swcs.AddKillicon("weapon_swcs_knife_gg", "hud/swcs/select/knifegg.png")
killicon.AddAlias("weapon_swcs_knife_ghost", "weapon_swcs_knife_flip")
swcs.AddKillicon("weapon_swcs_knife_gut", "hud/swcs/select/knife_gut.png")
swcs.AddKillicon("weapon_swcs_knife_gypsy_jackknife", "hud/swcs/select/knife_gypsy_jackknife.png")
swcs.AddKillicon("weapon_swcs_knife_karambit", "hud/swcs/select/knife_karambit.png")
swcs.AddKillicon("weapon_swcs_knife_m9_bayonet", "hud/swcs/select/knife_m9_bayonet.png")
swcs.AddKillicon("weapon_swcs_knife_outdoor", "hud/swcs/select/knife_outdoor.png")
swcs.AddKillicon("weapon_swcs_knife_push", "hud/swcs/select/knife_push.png")
swcs.AddKillicon("weapon_swcs_knife_skeleton", "hud/swcs/select/knife_skeleton.png")
swcs.AddKillicon("weapon_swcs_knife_stiletto", "hud/swcs/select/knife_stiletto.png")
swcs.AddKillicon("weapon_swcs_knife_survival_bowie", "hud/swcs/select/knife_survival_bowie.png")
swcs.AddKillicon("weapon_swcs_knife_tactical", "hud/swcs/select/knife_tactical.png")
swcs.AddKillicon("weapon_swcs_knife_ursus", "hud/swcs/select/knife_ursus.png")
swcs.AddKillicon("weapon_swcs_knife_widowmaker", "hud/swcs/select/knife_widowmaker.png")
swcs.AddKillicon("weapon_swcs_knife_kukri", "hud/swcs/select/knife_kukri.png")

swcs.AddKillicon("weapon_swcs_fists", "hud/swcs/select/fists.png")
swcs.AddKillicon("weapon_swcs_axe", "hud/swcs/select/axe.png")
swcs.AddKillicon("weapon_swcs_hammer", "hud/swcs/select/hammer.png")
swcs.AddKillicon("weapon_swcs_spanner", "hud/swcs/select/spanner.png")
swcs.AddKillicon("weapon_swcs_shield", "hud/swcs/select/shield.png")
swcs.AddKillicon("weapon_swcs_balshield", "hud/swcs/select/balshield.png")

swcs.AddKillicon("swcs_molotov_projectile", "hud/swcs/select/molotov.png")
swcs.AddKillicon("swcs_decoy_projectile", "hud/swcs/select/decoy.png")
swcs.AddKillicon("swcs_flashbang_projectile", "hud/swcs/select/flashbang.png")
swcs.AddKillicon("swcs_hegrenade_projectile", "hud/swcs/select/hegrenade.png")
swcs.AddKillicon("swcs_sensorgrenade_projectile", "hud/swcs/select/tagrenade.png")
swcs.AddKillicon("swcs_smokegrenade_projectile", "hud/swcs/select/smokegrenade.png")
swcs.AddKillicon("swcs_snowball_projectile", "hud/swcs/select/snowball.png")
swcs.AddKillicon("swcs_planted_c4", "hud/swcs/select/explosion.png")
killicon.AddAlias("swcs_breachcharge_projectile", "swcs_planted_c4")
