# spawnmenu
spawnmenu.category.swcs=CS:GO
spawnmenu.category.swcs_knives=Ножи из CS:GO
spawnmenu.menu.swcs_stattrak=StatTrak
spawnmenu.menu.swcs_apply_stattrak=Добавить StatTrak
spawnmenu.menu.swcs_remove_stattrak=Удалить StatTrak
spawnmenu.menu.swcs_reset_stattrak=Сбросить счётчик StatTrak
spawnmenu.menu.swcs_uid=Именной ярлык
spawnmenu.menu.swcs_apply_uid=Добавить Именной ярлык
spawnmenu.menu.swcs_edit_uid=Редактировать Именной ярлык
spawnmenu.menu.swcs_remove_uid=Удалить Именной ярлык
swcs.edit_uid.menu_title=Редактировать Именной ярлык
swcs.edit_uid.menu_desc=Введите новое имя для своего оружия:\nБудут применены фильтры Steam.

spawnmenu.menu.swcs_reset_cvars=Сбросить всё

spawnmenu.menu.swcs.sv_settings_name=Серверные настройки
spawnmenu.menu.swcs.sv_settings_header=Различные серверные настройки. Для их изменения необходимо быть админом.

spawnmenu.menu.swcs_spawnmenu_settings_header=Настройки спавнменю
spawnmenu.menu.swcs_spawnmenu_settings_desc=Чтобы изменения ниже вошли в силу, необходима перезагрузка спавнменю
spawnmenu.menu.swcs_spawnmenu_reload=Перезагрузить спавнменю

spawnmenu.menu.swcs.cl_settings_name=Клиентские настройки
spawnmenu.menu.swcs_cl_settings_header=Различные клиентские настройки.

spawnmenu.menu.swcs_crosshair_settings_name=Настройки прицела

spawnmenu.menu.swcs_viewmodel_settings_name=Настройки модели
spawnmenu.menu.swcs_viewmodel_settings_header=Влияет на то, как выглядит модель от первого лица.

spawnmenu.menu.swcs_hands_settings_name=Руки
spawnmenu.menu.swcs_hands_settings_header=Влияет на то, как выглядят руки от первого лица.

# sv cvars
spawnmenu.menu.swcs_cvar_sync_seed=Синхронизировать сид пулевого разброса
spawnmenu.menu.swcs_cvar_sync_seed_desc=Определяет, должна ли быть синхронизация сида пулевого разброса между сервером и клиентом.\nПри отключении, читерам сложнее предсказать сид разброса на сервере.
spawnmenu.menu.swcs_cvar_nospread=Отключить разброс у оружий
#spawnmenu.menu.swcs_cvar_nospread_desc=Whether or not to enable weapon nospread.\nDisabling makes it harder for cheaters to predict where their bullets will land.
spawnmenu.menu.swcs_cvar_individual_ammo=Патроны привязаны к оружию
spawnmenu.menu.swcs_cvar_individual_ammo_desc=Патроны будут хранится на оружии, а не на игроке. Резервные патроны могут быть восполнены только с помощью коробок с боезапасами.
spawnmenu.menu.swcs_cvar_shotgun_spread=Паттерны разброса для дробовиков
#spawnmenu.menu.swcs_cvar_shotgun_spread_desc=Whether or not to use per-weapon spread patterns.\nDisabling makes shotguns use random spread for pellets.
spawnmenu.menu.swcs_cvar_helmet_spawn=Давать игрокам шлем при спавне
spawnmenu.menu.swcs_cvar_defuser_spawn=Давать игрокам набор сапера при спавне
spawnmenu.menu.swcs_cvar_recoil_scale=Отдача оружия
spawnmenu.menu.swcs_cvar_show_impacts=Попадания пулей
spawnmenu.menu.swcs_cvar_show_impacts_desc=0 - Выключено\n1 - Клиент и сервер\n2 - Только клиент\n3 - Только сервер\n\nДля работы конвар \"developer\" необходимо выставить на \"1\".
spawnmenu.menu.swcs_cvar_deploy_speed_mult=Скорость доставания
spawnmenu.menu.swcs_cvar_damage_mult=Урон оружия
spawnmenu.menu.swcs_cvar_damage_mult_desc=Урон умножается на это значение.
spawnmenu.menu.swcs_cvar_headshot_damage_mult=Урон в голову
spawnmenu.menu.swcs_cvar_headshot_damage_mult_desc=Урон от выстрела в голову умножается на это значение, умноженное на урон от попадания в часть тела.

# cl vars
spawnmenu.menu.swcs_cvar_experm_interp=Экспериментальное сглаживание
spawnmenu.menu.swcs_cvar_csgo_impacts=Эффекты попаданий из CS:GO
spawnmenu.menu.swcs_cvar_csgo_blood=Эффекты крови из CS:GO
spawnmenu.menu.swcs_cvar_barrel_smoke=Дым из дула оружия
spawnmenu.menu.swcs_cvar_barrel_heat=Нагрев ствола пулемётов

spawnmenu.menu.swcs_cvar_updated_icon=Использовать обновлённую иконку из CS:GO
spawnmenu.menu.swcs_cvar_knives_unified_category=Показывать ножи в основной категории
spawnmenu.menu.swcs_cvar_group_others=Группировать категории аддонов SWCS под категорию CS:GO
spawnmenu.menu.swcs_cvar_view_dip=Приопускать камеру после приземления

# crosshair settings
spawnmenu.menu.swcs_import_crosshair_code=Импорт кода
spawnmenu.menu.swcs_import_crosshair_code_desc=Вставьте сюда код прицела для импорта.
spawnmenu.menu.swcs_export_crosshair_code=Экспорт кода
spawnmenu.menu.swcs_export_crosshair_code_desc=Нажмите для сохранения кода в буфер обмена.
spawnmenu.menu.swcs_import_crosshair_desc=Импорт/экспорт кода прицела.
spawnmenu.menu.swcs_crosshair_use_custom=Использовать свой прицел
spawnmenu.menu.swcs_crosshair_use_spectator=Показывать чужие прицелы
spawnmenu.menu.swcs_crosshair_follow_recoil=Следовать за отдачей оружия

spawnmenu.menu.swcs_crosshair_style=Стиль прицела
spawnmenu.menu.swcs_crosshair_style_default=Стандартный
spawnmenu.menu.swcs_crosshair_style_default_static=Стандартный (Статичный)
spawnmenu.menu.swcs_crosshair_style_accurate_split=Точный (Двойной)
spawnmenu.menu.swcs_crosshair_style_accurate_dynamic=Точный (Динамичный)
spawnmenu.menu.swcs_crosshair_style_classic_static=Классический (Статичный)
spawnmenu.menu.swcs_crosshair_style_classic_dynamic=Классический (Динамичный)

spawnmenu.menu.swcs_crosshair_color=Цвет
spawnmenu.menu.swcs_crosshair_color_red=Красный
spawnmenu.menu.swcs_crosshair_color_green=Зелёный
spawnmenu.menu.swcs_crosshair_color_yellow=Жёлтый
spawnmenu.menu.swcs_crosshair_color_blue=Синий
spawnmenu.menu.swcs_crosshair_color_cyan=Голубой
spawnmenu.menu.swcs_crosshair_color_custom=Свой

spawnmenu.menu.swcs_crosshair_outline=Обводка
spawnmenu.menu.swcs_crosshair_outline_thickness=Толщина обводки

spawnmenu.menu.swcs_crosshair_use_alpha=Использовать прозрачность

spawnmenu.menu.swcs_crosshair_t=Т-образный прицел
spawnmenu.menu.swcs_crosshair_dot=Точка в центре
spawnmenu.menu.swcs_crosshair_thickness=Толщина
spawnmenu.menu.swcs_crosshair_size=Длина
spawnmenu.menu.swcs_crosshair_center_gap=Зазор
spawnmenu.menu.swcs_crosshair_weapon_gap=Зазор зависит от оружия

# viewmodel settings
spawnmenu.menu.swcs_viewmodel_fov=FOV модели
spawnmenu.menu.swcs_viewmodel_offset_x=Отступ по X
spawnmenu.menu.swcs_viewmodel_offset_y=Отступ по Y
spawnmenu.menu.swcs_viewmodel_offset_z=Отступ по Z
spawnmenu.menu.swcs_viewmodel_recoil_tracking=Отдача модели
spawnmenu.menu.swcs_viewmodel_headbob_style=Тряска
spawnmenu.menu.swcs_viewmodel_headbob_style_gmod=Стандартная из GMod
spawnmenu.menu.swcs_viewmodel_headbob_style_csgo=CS:GO
spawnmenu.menu.swcs_viewmodel_headbob_style_old=Старая CS
spawnmenu.menu.swcs_viewmodel_bob_frequency=Частота тряски
spawnmenu.menu.swcs_viewmodel_bob_vertical=Тряска по вертикали
spawnmenu.menu.swcs_viewmodel_bob_lateral=Тряска по горизонтали
spawnmenu.menu.swcs_viewmodel_bob_loweramt=Тряска вниз
spawnmenu.menu.swcs_viewmodel_lowering_angle=Угол опускания
spawnmenu.menu.swcs_viewmodel_lowering_speed=Скорость опускания
spawnmenu.menu.swcs_viewmodel_tracers_fp=Рисовать трассеры пуль от первого лица
spawnmenu.menu.swcs_viewmodel_tracers_move=Двигать трассеры пуль от пересечений с миром
spawnmenu.menu.swcs_viewmodel_ironsight_blur=Размытие при прицеле
spawnmenu.menu.swcs_viewmodel_righthand=Оружие в правой руке

# hands settings
spawnmenu.menu.swcs_hands_model=Модель рук
spawnmenu.menu.swcs_hands_skin=Оттенок кожи
spawnmenu.menu.swcs_hands_sleeves=Модель рукавов

# weapon categories
spawnmenu.category.swcs_pistols=Пистолеты
spawnmenu.category.swcs_rifles=Винтовки
spawnmenu.category.swcs_shotguns=Дробовики
spawnmenu.category.swcs_smgs=Пистолеты-пулемёты
spawnmenu.category.swcs_mgs=Пулемёты
spawnmenu.category.swcs_snipers=Снайперские винтовки
spawnmenu.category.swcs_grenades=Гранаты
spawnmenu.category.swcs_knives=Ножи
spawnmenu.category.swcs_melee=Ближний бой

# spawnables
swcs_ammo_generic=Коробка боеприпасов
swcs_defuser=Набор сапёра
swcs_helmet_kevlar=Бронежилет + Шлем
swcs_helmet=Шлем
swcs_kevlar=Бронежилет
swcs_snowball_pile=Куча снежков

# ammo
BULLET_PLAYER_50AE_ammo=Боеприпасы .50 AE
BULLET_PLAYER_762MM_ammo=Боеприпасы 7.62mm
BULLET_PLAYER_556MM_ammo=Боеприпасы 5.56mm
BULLET_PLAYER_556MM_SMALL_ammo=Боеприпасы 5.56mm (Маленькие)
BULLET_PLAYER_556MM_BOX_ammo=Боеприпасы 5.56mm (Коробка)
BULLET_PLAYER_338MAG_ammo=Боеприпасы магнума .338
BULLET_PLAYER_9MM_ammo=Боеприпасы 9mm
BULLET_PLAYER_BUCKSHOT_ammo=Картечные боеприпасы
BULLET_PLAYER_45ACP_ammo=Боеприпасы .45 ACP
BULLET_PLAYER_57MM_ammo=Боеприпасы 5.7mm
BULLET_PLAYER_357SIG_ammo=Боеприпасы .357 SIG
BULLET_PLAYER_357SIG_SMALL_ammo=Боеприпасы .357 SIG (Маленькие)
BULLET_PLAYER_357SIG_MIN_ammo=Боеприпасы .357 SIG (Минимальные)
BULLET_PLAYER_357SIG_P250_ammo=Боеприпасы .357 SIG (P250)

swcs_flashbang_ammo=Световые гранаты
swcs_hegrenade_ammo=Осколочные гранаты
swcs_smokegrenade_ammo=Дымовые гранаты
swcs_firegrenade_ammo=Зажигательные гранаты
swcs_snowball_ammo=Снежки
swcs_tagrenade_ammo=Тактические гранаты
swcs_healthshot_ammo=Медицинские шприцы
swcs_decoygrenade_ammo=Ложные гранаты
swcs_breachcharge_ammo=Подрывные заряды

# gameplay
swcs.switched_to_burst=Переключено в режим стрельбы очередями
swcs.switched_to_auto=Переключено в автоматический режим
swcs.c4_defuse_mustbeonground=Вы должны стоять на земле, чтобы обезвредить бомбу
swcs.c4_plant_mustbeonground=Вы должны стоять на земле, чтобы заложить C4
swcs.c4_plant_atsite=C4 необходимо установить на месте закладки бомбы
swcs.shield_onlyone=У вас уже есть щит.
swcs.weapon_name_stattrak=StatTrak™ %s