# spawnmenu
spawnmenu.category.swcs=CS:GO
spawnmenu.category.swcs_knives=CS:GO Knives
spawnmenu.menu.swcs_stattrak=StatTrak
spawnmenu.menu.swcs_apply_stattrak=Add StatTrak
spawnmenu.menu.swcs_remove_stattrak=Remove StatTrak
spawnmenu.menu.swcs_reset_stattrak=Reset StatTrak counter
spawnmenu.menu.swcs_uid=Name Tag
spawnmenu.menu.swcs_apply_uid=Add Name Tag
spawnmenu.menu.swcs_edit_uid=Edit Name Tag
spawnmenu.menu.swcs_remove_uid=Remove Name Tag
swcs.edit_uid.menu_title=Edit Name Tag
swcs.edit_uid.menu_desc=Enter a new name for your weapon:\nSteam filtering applies.

spawnmenu.menu.swcs_reset_cvars=Reset All

spawnmenu.menu.swcs.sv_settings_name=Serverside Settings
spawnmenu.menu.swcs.sv_settings_header=Miscellaneous serverside settings. These require you to be admin to change.

spawnmenu.menu.swcs_spawnmenu_settings_header=Spawnmenu Settings
spawnmenu.menu.swcs_spawnmenu_settings_desc=Requires reloading of the spawnmenu to take effect
spawnmenu.menu.swcs_spawnmenu_reload=Reload Spawnmenu

spawnmenu.menu.swcs.cl_settings_name=Clientside Settings
spawnmenu.menu.swcs_cl_settings_header=Miscellaneous clientside settings.

spawnmenu.menu.swcs_crosshair_settings_name=Crosshair Settings

spawnmenu.menu.swcs_viewmodel_settings_name=Viewmodel Settings
spawnmenu.menu.swcs_viewmodel_settings_header=Affects how your viewmodel looks.

spawnmenu.menu.swcs_hands_settings_name=Hands
spawnmenu.menu.swcs_hands_settings_header=Affects how your hands look.

# sv cvars
spawnmenu.menu.swcs_cvar_sync_seed=Sync bullet spread seed
spawnmenu.menu.swcs_cvar_sync_seed_desc=Whether or not the bullet spread seed should be synced between server and client.\nDisabling makes it harder for cheaters to predict what the spread seed is serverside.
spawnmenu.menu.swcs_cvar_nospread=Enable weapon nospread
#spawnmenu.menu.swcs_cvar_nospread_desc=Whether or not to enable weapon nospread.\nDisabling makes it harder for cheaters to predict where their bullets will land.
spawnmenu.menu.swcs_cvar_individual_ammo=Individual weapon ammo
spawnmenu.menu.swcs_cvar_individual_ammo_desc=Ammo is stored on the weapon instead of the player. Reserve ammo can only be replenished using ammo boxes.
spawnmenu.menu.swcs_cvar_hl2_ammo=Use default ammo types
spawnmenu.menu.swcs_cvar_hl2_ammo_desc=Guns will use default Half-Life 2 ammo types instead of custom ones.
spawnmenu.menu.swcs_cvar_shotgun_spread=Shotgun spread patterns
#spawnmenu.menu.swcs_cvar_shotgun_spread_desc=Whether or not to use per-weapon spread patterns.\nDisabling makes shotguns use random spread for pellets.
spawnmenu.menu.swcs_cvar_helmet_spawn=Give players a helmet on spawn
spawnmenu.menu.swcs_cvar_defuser_spawn=Give players a defuser on spawn
spawnmenu.menu.swcs_cvar_recoil_scale=Weapon recoil scale
spawnmenu.menu.swcs_cvar_show_impacts=Show bullet impacts
spawnmenu.menu.swcs_cvar_show_impacts_desc=0 - Off\n1 - Client and Server\n2 - Client only\n3 - Server only\n\nRequires \"developer\" cvar set to \"1\" to see.
spawnmenu.menu.swcs_cvar_deploy_speed_mult=Deploy speed multiplier
spawnmenu.menu.swcs_cvar_damage_mult=Weapon damage scale
spawnmenu.menu.swcs_cvar_damage_mult_desc=Damage is multiplied by this value.
spawnmenu.menu.swcs_cvar_headshot_damage_mult=Headshot damage scale
spawnmenu.menu.swcs_cvar_headshot_damage_mult_desc=Headshot damage is multiplied by this value, multiplicative with hitgroup scale.

# cl vars
spawnmenu.menu.swcs_cvar_experm_interp=Experimental Smoothing
spawnmenu.menu.swcs_cvar_csgo_impacts=CS:GO Impact Effects
spawnmenu.menu.swcs_cvar_csgo_blood=CS:GO Blood Effects
spawnmenu.menu.swcs_cvar_barrel_smoke=Weapon barrel smoke
spawnmenu.menu.swcs_cvar_barrel_heat=LMG barrel heat

spawnmenu.menu.swcs_cvar_updated_icon=Use the updated CS:GO icon
spawnmenu.menu.swcs_cvar_knives_unified_category=Show knives in main category
spawnmenu.menu.swcs_cvar_group_others=Group SWCS addon categories under CS:GO category
spawnmenu.menu.swcs_cvar_view_dip=View dips down when landing a jump
spawnmenu.menu.swcs_cvar_enable_hl2_zoom=Enable default zoom bind behavior
spawnmenu.menu.swcs_cvar_contextual_zoom=Zoom bind affects scope on weapons
spawnmenu.menu.swcs_cvar_candycorn=Enable candy corn shell casings during Halloween

# crosshair settings
spawnmenu.menu.swcs_import_crosshair_code=Import Code
spawnmenu.menu.swcs_import_crosshair_code_desc=Paste a crosshair code here to import it.
spawnmenu.menu.swcs_export_crosshair_code=Export Code
spawnmenu.menu.swcs_export_crosshair_code_desc=Click to copy this code to your clipboard.
spawnmenu.menu.swcs_import_crosshair_desc=Import/Export crosshair codes.
spawnmenu.menu.swcs_crosshair_use_custom=Use custom crosshair
spawnmenu.menu.swcs_crosshair_use_spectator=Use spectating target's crosshair
spawnmenu.menu.swcs_crosshair_follow_recoil=Follow weapon recoil

spawnmenu.menu.swcs_crosshair_style=Crosshair style
spawnmenu.menu.swcs_crosshair_style_default=Default
spawnmenu.menu.swcs_crosshair_style_default_static=Default (Static)
spawnmenu.menu.swcs_crosshair_style_accurate_split=Accurate (Split)
spawnmenu.menu.swcs_crosshair_style_accurate_dynamic=Accurate (Dynamic)
spawnmenu.menu.swcs_crosshair_style_classic_static=Classic (Static)
spawnmenu.menu.swcs_crosshair_style_classic_dynamic=Classic (Dynamic)

spawnmenu.menu.swcs_crosshair_color=Color
spawnmenu.menu.swcs_crosshair_color_red=Red
spawnmenu.menu.swcs_crosshair_color_green=Green
spawnmenu.menu.swcs_crosshair_color_yellow=Yellow
spawnmenu.menu.swcs_crosshair_color_blue=Blue
spawnmenu.menu.swcs_crosshair_color_cyan=Cyan
spawnmenu.menu.swcs_crosshair_color_custom=Custom

spawnmenu.menu.swcs_crosshair_outline=Outline
spawnmenu.menu.swcs_crosshair_outline_thickness=Outline thickness

spawnmenu.menu.swcs_crosshair_use_alpha=Use alpha

spawnmenu.menu.swcs_crosshair_t=Tee-style crosshair
spawnmenu.menu.swcs_crosshair_dot=Center dot
spawnmenu.menu.swcs_crosshair_thickness=Pip thickness
spawnmenu.menu.swcs_crosshair_size=Pip size
spawnmenu.menu.swcs_crosshair_center_gap=Center gap
spawnmenu.menu.swcs_crosshair_weapon_gap=Use weapon's crosshair gap value

# viewmodel settings
spawnmenu.menu.swcs_viewmodel_fov=View model FOV
spawnmenu.menu.swcs_viewmodel_offset_x=Offset X
spawnmenu.menu.swcs_viewmodel_offset_y=Offset Y
spawnmenu.menu.swcs_viewmodel_offset_z=Offset Z
spawnmenu.menu.swcs_viewmodel_recoil_tracking=Recoil tracking
spawnmenu.menu.swcs_viewmodel_headbob_style=Headbob style
spawnmenu.menu.swcs_viewmodel_headbob_style_gmod=Default GMod
spawnmenu.menu.swcs_viewmodel_headbob_style_csgo=CS:GO
spawnmenu.menu.swcs_viewmodel_headbob_style_old=Old CS
spawnmenu.menu.swcs_viewmodel_bob_frequency=Bob frequency
spawnmenu.menu.swcs_viewmodel_bob_vertical=Vertical bob amount
spawnmenu.menu.swcs_viewmodel_bob_lateral=Lateral bob amount
spawnmenu.menu.swcs_viewmodel_bob_loweramt=Bob lower amount
spawnmenu.menu.swcs_viewmodel_lowering_angle=Lowering angle
spawnmenu.menu.swcs_viewmodel_lowering_speed=Lowering speed
spawnmenu.menu.swcs_viewmodel_tracers_fp=Draw bullet tracers in first person
spawnmenu.menu.swcs_viewmodel_tracers_move=Move bullet tracers to not intersect with world
spawnmenu.menu.swcs_viewmodel_ironsight_blur=Blur on ironsight weapons
spawnmenu.menu.swcs_viewmodel_righthand=Right handedness on view models

# hands settings
spawnmenu.menu.swcs_hands_model=Hands model
spawnmenu.menu.swcs_hands_skin=Skin tone
spawnmenu.menu.swcs_hands_sleeves=Sleeves model

# weapon categories
spawnmenu.category.swcs_pistols=Pistols
spawnmenu.category.swcs_rifles=Rifles
spawnmenu.category.swcs_shotguns=Shotguns
spawnmenu.category.swcs_smgs=SMGs
spawnmenu.category.swcs_mgs=Machine guns
spawnmenu.category.swcs_snipers=Sniper rifles
spawnmenu.category.swcs_grenades=Grenades
spawnmenu.category.swcs_knives=Knives
spawnmenu.category.swcs_melee=Melee

# spawnables
swcs_ammo_generic=Ammo Box
swcs_defuser=Defuse Kit
swcs_helmet_kevlar=Kevlar + Helmet
swcs_helmet=Helmet
swcs_kevlar=Kevlar
swcs_snowball_pile=Snowball Pile

# ammo
BULLET_PLAYER_50AE_ammo=.50 AE Ammo
BULLET_PLAYER_762MM_ammo=7.62mm Ammo
BULLET_PLAYER_556MM_ammo=5.56mm Ammo
BULLET_PLAYER_556MM_SMALL_ammo=5.56mm (Small) Ammo
BULLET_PLAYER_556MM_BOX_ammo=5.56mm (Box) Ammo
BULLET_PLAYER_338MAG_ammo=.338 Magnum Ammo
BULLET_PLAYER_9MM_ammo=9mm Ammo
BULLET_PLAYER_BUCKSHOT_ammo=Buckshot Ammo
BULLET_PLAYER_45ACP_ammo=.45 ACP Ammo
BULLET_PLAYER_57MM_ammo=5.7mm Ammo
BULLET_PLAYER_357SIG_ammo=.357 SIG Ammo
BULLET_PLAYER_357SIG_SMALL_ammo=.357 SIG (Small) Ammo
BULLET_PLAYER_357SIG_MIN_ammo=.357 SIG (Min) Ammo
BULLET_PLAYER_357SIG_P250_ammo=.357 SIG (P250) Ammo

swcs_flashbang_ammo=Flashbangs
swcs_hegrenade_ammo=HE Grenades
swcs_smokegrenade_ammo=Smoke Grenades
swcs_firegrenade_ammo=Fire Grenades
swcs_snowball_ammo=Snowballs
swcs_tagrenade_ammo=T.A. Grenades
swcs_healthshot_ammo=Healthshots
swcs_decoygrenade_ammo=Decoy Grenades
swcs_breachcharge_ammo=Breach Charges

# gameplay
swcs.switched_to_burst=Switched to burst-fire mode
swcs.switched_to_auto=Switched to automatic
swcs.c4_defuse_mustbeonground=Must be on ground to defuse C4
swcs.c4_plant_mustbeonground=Must be on ground to plant C4
swcs.c4_plant_atsite=C4 must be planted at bomb site
swcs.shield_onlyone=You already have a shield.
swcs.weapon_name_stattrak=StatTrak™ %s
swcs.weapon_possessive=%s1's %s2

# ttt sv settings
swcs.ttt_sv_cvar_enable_replace.label=Enable weapon replacement
swcs.ttt_sv_cvar_enable_replace.help=Enable to replace stock TTT weapons with CS:GO weapons.

swcs.ttt_sv_cvar_disable_replace_crowbar.label=Disable replacing crowbar
swcs.ttt_sv_cvar_disable_replace_crowbar.help=Disables replacing crowbar with knives when using the CS:GO weapon replacer.

swcs.ttt_sv_cvar_always_replace_crowbar.label=Always replace crowbar
swcs.ttt_sv_cvar_always_replace_crowbar.help=Replaces crowbar with knives regardless of the weapon replacement setting.

swcs.ttt_sv_cvar_ignore_category.label=Ignore weapon category
swcs.ttt_sv_cvar_ignore_category.help=Allows weapons that aren't explicitly in the CS:GO category to be added to the spawnlist or their equipments to be bought.

swcs.ttt_sv_cvar_prevent_others.label=Prevent non-CS:GO weapons from spawning

# ttt spawnlist editor
swcs.ttt_spawnlist_editor.open=Open Spawnlist Editor
swcs.ttt_spawnlist_editor.title=Spawnlist Editor
swcs.ttt_spawnlist_editor.upload=Upload to Server

swcs.ttt_spawnlist_editor.allowed_title=Allowed Weapons
swcs.ttt_spawnlist_editor.disallowed_title=Disallowed Weapons

swcs.ttt_spawnlist_editor.add_selected_one=Add
swcs.ttt_spawnlist_editor.add_selected_multiple=Add Selected
swcs.ttt_spawnlist_editor.remove_selected_one=Remove
swcs.ttt_spawnlist_editor.remove_selected_multiple=Remove Selected

# ttt cl settings
swcs.ttt_cl_cvar_knife.label=Knife
swcs.ttt_cl_cvar_knife.help=When CS:GO weapons are enabled, your preferred knife will be given at spawn.
